# Generated by Django 5.2.16 on 2026-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mualif', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
